spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/biological_science
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  aop:
    auto: true
    proxy-target-class: true
mybatis:
  configuration:
    # 开启驼峰命名方式
    map-underscore-to-camel-case: true
# 开启 Mybatis 日志输出
logging:
  level:
    com.neutech.mammalia.mapper: TRACE
server:
  port: 8080
  servlet:
    context-path: /api